kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.name }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Chart.nfs.storage }}
